baseURL = 'https://mags.nu/'
theme = "hugo-bearcub"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']

[params]
themeStyle = "herman"
copyright = '© 2024 Magnus Sletfjerding'
  [params.author]
    email = 'contact-blog@mail.mags.nu'
    name = 'Mags'

[languages]
  [languages.en]
    title = 'Magnus Berg Sletfjerding'
    languageName = "en-US 🇺🇸"
    languageCode = 'en-us'
    contentDir = "content"
    [languages.en.params]
